name: CupBoard-fork
main: tw.mics.spigot.plugin.cupboard.Cupboard
version: ${project.version}
description: ${project.description}
author: Mics
authors: [Mics, Domo, wenwen357951(WenWen_xD)]
website: https://mics.tw
api-version: 1.21

commands:
  gold:
    description: Manage your gold block
    usage: /gold give <player> or /gold nearest
    
permissions:
  cupboard.admin:
    description: this can reload cupboard config
    default: op
  cupboard.bypass:
    description: this can let player bypass cupboard protect
    default: op