name: CupBoard
main: com.mics.spigotPlugin.cupboard.Cupboard
version: 1.3.0
commands:
  kill:
    description: kill yourself
    aliases: [suicide]
    usage: /kill
  cupboardreload:
    description: Reload cupboard config
    usage: /cupboardreload
    permission: cupboard.admin
  airdrop:
    description: Reload cupboard config
    usage: /airdrop <x> <z>
    permission: cupboard.admin
    
permissions:
  cupboard.admin:
    description: this can reload cupboard config
    default: op